### ISSUE TITLE
Neoscan in Privatenet

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#406]
Hi @adrienmo, 
    After the removal of notification our neoscan has not been performing perfectly in terms of syncing.
   It is getting stuck very often, while the neo-clients keep generating blocks normally.

   I believe it is part due to some of our configurations. Can you please check if the way we are setting the containers is properly done?

```yaml
  eco-neo-scan-api-running:
    image: "registry.gitlab.com/cityofzion/neo-scan/api:56268341-master"
    container_name: "eco-neo-scan-api-running"
    ports:
      - "4000:4000"
    #command: /bin/true #disable neo-scan
    environment:
      PORT: 4000
      HOST: localhost
      NEO_SEEDS: "http://eco-neo-csharp-node1-running:30333;http://eco-neo-csharp-noderpc1-running:30334;http://eco-neo-csharp-noderpc1-running:30337"
      DB_HOSTNAME: eco-neo-scan-postgresql-running
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    depends_on:
      - eco-neo-scan-postgresql-running
      - eco-neo-scan-sync-running
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-noderpc1-running
    entrypoint: bash -c "sleep 10 && /start.sh"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4000
      timeout: 10s
    networks:
      - neo_scan_internal
      - private_net

  eco-neo-scan-sync-running:
    container_name: "eco-neo-scan-sync-running"
    image: "registry.gitlab.com/cityofzion/neo-scan/sync:56268341-master"
    depends_on:
      - eco-neo-scan-postgresql-running
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
    environment:
      NEO_SEEDS: "http://eco-neo-csharp-node1-running:30333;http://eco-neo-csharp-noderpc1-running:30334;http://eco-neo-csharp-noderpc1-running:30337"
      DB_HOSTNAME: eco-neo-scan-postgresql-running
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    entrypoint: bash -c "sleep 5 && /start.sh"
    networks:
      - neo_scan_internal
      - private_net

  eco-neo-scan-postgresql-running:
    image: postgres:10.5
    container_name: "eco-neo-scan-postgresql-running"
    expose:
      - 5432
    depends_on:
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/5432
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - neo_scan_internal
```
